-- 001_init.sql
-- Generated by drizzle-kit — do not edit directly.
-- GIN indexes added manually (drizzle-kit doesn't emit these).

CREATE TABLE IF NOT EXISTS "recruiters" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "company" text NOT NULL,
  "name" text,
  "email" text NOT NULL,
  "title" text,
  "linkedin_url" text,
  "github_url" text,
  "location" text,
  "status" text DEFAULT 'active',
  "verified_at" timestamptz,
  "source_date" date,
  "response_rate" numeric(5, 2),
  "avg_reply_days" integer,
  "students_placed" integer DEFAULT 0,
  "accolades" text[] DEFAULT '{}',
  "role_tags" text[] DEFAULT '{}',
  "industry_tags" text[] DEFAULT '{}',
  "raw_linkedin" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "student_saves" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "student_id" uuid NOT NULL,
  "recruiter_id" uuid NOT NULL REFERENCES "recruiters"("id") ON DELETE CASCADE,
  "created_at" timestamptz DEFAULT now()
);

-- unique indexes
CREATE UNIQUE INDEX IF NOT EXISTS "recruiters_email_idx" ON "recruiters" ("email");
CREATE INDEX IF NOT EXISTS "recruiters_company_idx" ON "recruiters" ("company");
CREATE UNIQUE INDEX IF NOT EXISTS "student_saves_unique_idx" ON "student_saves" ("student_id", "recruiter_id");

-- GIN indexes for array overlap queries (?| operator)
CREATE INDEX IF NOT EXISTS "recruiters_accolades_gin" ON "recruiters" USING GIN ("accolades");
CREATE INDEX IF NOT EXISTS "recruiters_role_tags_gin" ON "recruiters" USING GIN ("role_tags");
CREATE INDEX IF NOT EXISTS "recruiters_industry_tags_gin" ON "recruiters" USING GIN ("industry_tags");

-- updated_at trigger
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER recruiters_updated_at
  BEFORE UPDATE ON "recruiters"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
